introFile = open("usamaFile")
# print(introFile.readline())
# print("===========================")
# print(introFile.tell())
# print(introFile.readlines())
# print(introFile.tell())
introFile.seek(10)
print(introFile.readline())
introFile.close()